fail_fast: true
repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: ruff format --diff
        language: python
        always_run: true
        types:
          - python
        additional_dependencies:
          - ruff
      - id: lint
        name: lint
        entry: ruff check
        language: python
        always_run: true
        types:
          - python
        additional_dependencies:
          - ruff
      - id: type-checker
        name: type checker
        entry: pyright
        language: python
        always_run: true
        types:
          - python
        additional_dependencies:
          - pydantic
          - pyright