[tool.poetry]
name = "mini-framework"
version = "0.0.1"
description = "This is a mini framework that only supports CRUD operations. THIS ONLY FOR EDUCATIONAL PURPOSES."
authors = ["Vladyslav Timofeev <Timofeevvladyslav49@gmail.com>"]
readme = "README.md"
packages = [{include = "mini_framework", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev]
optional = true


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
flake8 = "^7.0.0"
httpx = "^0.26.0"
black = "^23.12.1"
flake8-commas = "^2.1.0"
flake8-import-order = "^0.18.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
